---
- name: Install Apache and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-php5

- name: Activate mod_rewrite
  apache2_module: name=rewrite state=present

- name: Activate mod_deflate
  apache2_module: name=deflate state=present

- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-mysql
    - php5-xmlrpc

- name: Copy virtual host setup over
  template: src={{ vhostTemplatePath }} dest={{ws_vhost_path}}/{{item.key}}
  with_dict: sites

- name: Activate virtual host
  command: a2ensite {{item.key}}
  with_dict: sites

#- name: Deactivate default vhost
#  command: a2dissite 000-default

- name: Ensure Apache is running
  service: name=apache2 state=restarted enabled=yes

- name: wait for apache2 to start
  wait_for: port={{http_port}}
