---
- name: Install Apache and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-php5

- name: Activate mod_rewrite
  apache2_module: name=rewrite state=present
- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
	- php5
	- php5-cli
	- php5-curl
	- php5-gd
	- php5-imagick
	- php5-mysql
	- php5-xmlrpc

- name: Install Apache and its modules
  apt: pkg={{ item }} state=latest
  with_items:
	- apache2
	- libapache2-mod-php5

- name: Ensure Apache is running
  service: name=apache2 state=restarted enabled=yes

#    - name: Copy virtual host setup over
#      template: src={{ vhostTemplatePath }} dest=/etc/apache2/sites-available/

#    - name: Activate virtual host
#      command: a2ensite vhost

#    - name: Deactivate default vhost
#      command: a2dissite 000-default